export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const TOGGLE_HEADER = 'TOGGLE_HEADER';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
